KAFKA_SERVERS: ${HOST}
SHOW_SQL: true
SERVER_PORT: 8082
CMS_SERVICE_BASE_URL: http://${CMS_HOST}:8082/cms/
DB_HOST: ${HOST}
DB_PORT: 5432
DB_NAME: loyalty
DB_SCHEMA: voucher
DB_USER: postgres
DB_PASSWORD: postgres


