KAFKA_SERVERS: 54.249.128.2:9092
REDIS_HOST: 18.181.217.35
REDIS_PORT: 6379
SHOW_SQL: false
SERVER_PORT: 8082
DB_HOST: 18.181.217.35
DB_PORT: 5433
DB_NAME: loyalty
DB_SCHEMA: voucher
DB_USER: postgres
DB_PASSWORD: postgres
CMS_SERVICE_BASE_URL: http://localhost:8080




