version: '3.0'
services:
  postgres:
    image: postgres
    container_name: postgres-loyalty
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loyalty
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-loyalty
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data

  zookeeper:
    container_name: zookeeper-inventory
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper-data:/opt

  kafka:
    container_name: kafka-loyalty
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - kafka-data:/kafka
    depends_on:
      - zookeeper

#  kafka-rest:
#    image: nodefluent/kafka-rest
#    ports:
#      - "8082:8082"
#    links:
#      - kafka
#      - zookeeper
#    depends_on:
#      - kafka
#      - zookeeper
#    environment:
#      DEBUG: "*"
#
#  kafka-rest-ui:
#    image: nodefluent/kafka-rest-ui
#    ports:
#      - "80:8000"
#    links:
#      - kafka-rest
#    depends_on:
#      - kafka-rest
#    environment:
#      DEBUG: "*"
#      REACT_APP_KAFKA_REST_URL: "http://kafka-rest:8082/"
#      REACT_APP_TIMEOUT: "3000"
#      PROXY: "yes"
#      BASIC_AUTH_USER: "admin"
#      BASIC_AUTH_PASSWORD: "admin"

#  loyalty-cms:
#    image: loyalty-cms:1.1
#    container_name: cms
#    environment:
#      - "ACTIVE_PROFILE=local"
#      - "HOST=host.docker.internal"
#    ports:
#      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#  loyalty-voucher:
#    container_name: voucher
#    image: loyalty-voucher:1.1
#    environment:
#      - "ACTIVE_PROFILE=local"
#      - "HOST=host.docker.internal"
#      - "CMS_HOST=host.docker.internal"
#    ports:
#      - "8082:8082"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
  redis-data:
  zookeeper-data:
  kafka-data: