version: '3.0'
services:
  loyalty-transaction:
    image: toanbv1997/loyalty-transaction
    container_name: loyalty-transaction
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: 172.31.4.193
      DB_HOST: 172.31.4.193
      CMS_BASEURL: http://172.31.35.232:8080/cms/api/v1
      VOUCHER_BASEURL: http://172.31.35.232:8082/voucher/api/v1
  loyalty-client:
    image: toanbv1997/loyalty-client
    container_name: loyalty-client
    ports:
      - "80:3000"
    environment:
      CMS_BASEURL: http://172.31.35.232:8080
      VOUCHER_BASEURL:  http://172.31.35.232:8082
      TRANSACTION_BASEURL: http://loyalty-transaction:8080
    depends_on:
      - loyalty-transaction