version: '3.0'
services:
  postgres:
    image: postgres
    container_name: postgres-loyalty
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loyalty
    volumes:
      - postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis
    container_name: redis-loyalty
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  loyalty-cms:
    image: toanbv1997/loyalty-cms
    container_name: loyalty-cms
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: loyalty
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CMS_BASEURL: http://loyalty-cms:8080/cms/api/v1
      VOUCHER_BASEURL: http://loyalty-voucher:8082/voucher/api/v1
      TRANSACTION_BASE_URL: http://loyalty-transaction:8083/transaction/api/v1
  loyalty-voucher:
    image: toanbv1997/loyalty-voucher
    container_name: loyalty-voucher
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: loyalty
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CMS_BASEURL: http://loyalty-cms:8080/cms/api/v1
      VOUCHER_BASEURL: http://loyalty-voucher:8082/voucher/api/v1
      TRANSACTION_BASE_URL: http://loyalty-transaction:8083/transaction/api/v1
  loyalty-transaction:
    image: toanbv1997/loyalty-transaction
    container_name: loyalty-transaction
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: loyalty
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CMS_BASEURL: http://loyalty-cms:8080/cms/api/v1
      VOUCHER_BASEURL: http://loyalty-voucher:8082/voucher/api/v1
      TRANSACTION_BASE_URL: http://loyalty-transaction:8083/transaction/api/v1
    depends_on:
      - loyalty-voucher
      - loyalty-cms
      - postgres
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  loyalty-client:
    image: toanbv1997/loyalty-client
    container_name: client
    ports:
      - "80:80"
    environment:
      CMS_BASEURL: http://172.31.30.46:8080/cms/api/v1
      VOUCHER_BASEURL: http://172.31.30.46:8082/voucher/api/v1
      TRANSACTION_BASE_URL: http://172.31.30.46:8083/transaction/api/v1
    depends_on:
      - loyalty-voucher
      - loyalty-cms
      - loyalty-transaction
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres-data:
  redis-data: