KAFKA_SERVERS: 54.249.128.2:9092
REDIS_HOST: 35.77.121.52
REDIS_PORT: 6379
SHOW_SQL: false
SERVER_PORT: 8080
DB_HOST: 35.77.121.52
DB_PORT: 5432
DB_NAME: loyalty
DB_SCHEMA: cms
DB_USER: postgres
DB_PASSWORD: postgres


