KAFKA_SERVERS: 18.181.217.35:9092
REDIS_HOST: 18.181.217.35
REDIS_PORT: 6379
SHOW_SQL: false
SERVER_PORT: 8080
DB_HOST: 18.181.217.35
DB_PORT: 5433
DB_NAME: loyalty
DB_SCHEMA: cms
DB_USER: postgres
DB_PASSWORD: postgres


