KAFKA_SERVERS: localhost:9092
SERVER_PORT: 8080
CMS_SERVICE_BASE_URL: http://localhost:8080
DB_HOST: ${:localhost}
DB_PORT: 5433
DB_NAME: loyalty
DB_SCHEMA: cms
DB_USER: postgres
DB_PASSWORD: postgres
