KAFKA_SERVERS: ${HOST}/9092
SHOW_SQL: false
SERVER_PORT: 8080
CMS_SERVICE_BASE_URL: http://localhost:8080/cms/
DB_HOST: ${HOST}
DB_PORT: 5433
DB_NAME: loyalty
DB_SCHEMA: cms
DB_USER: postgres
DB_PASSWORD: postgres
