HOST: ${HOST:loclahost}
KAFKA_SERVERS: 3.112.249.48:9092
REDIS_HOST: 3.112.249.48
REDIS_PORT: 6379
SHOW_SQL: false
SERVER_PORT: 8080
DB_HOST: 3.112.249.48
DB_PORT: 5433
DB_NAME: loyalty
DB_SCHEMA: cms
DB_USER: postgres
DB_PASSWORD: postgres


