# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-cms
  labels:
    app: loyalty-cms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loyalty-cms
  template:
    metadata:
      labels:
        app: loyalty-cms
    spec:
      containers:
        - name: cms
          image: toanbv1997/loyalty-cms:1.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.2"
              memory: 300Mi
            limits:
              cpu: "1.0"
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: loyalty-cms

---
# service
apiVersion: v1
kind: Service
metadata:
  name: loyalty-cms
  labels:
    app: loyalty-cms
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: loyalty-cms
