spring:
  application:
    name: loyalty-migration
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventory_db}?currentSchema=${DB_SCHEMA:inventory_schema}&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER:dev}
    password: ${DB_PASSWORD:password}
  profiles:
    active: ${ACTIVE_PROFILE:local}